### ISSUE TITLE
How to build ?

### ISSUE THREAD

**Issue by AzimovParviz** [lbajada/keycloak-multistep-registration#1]
I am building a .jar with maven and add it to the providers folder in keycloak. I get multiple
`[error]: Build step org.keycloak.quarkus.deployment.KeycloakProcessor#configureKeycloakSessionFactory threw an exception: java.lang.NoClassDefFoundError: org/keycloak/authentication/DisplayTypeRequiredActionFactory` when Keycloak is trying to build. Running 24.0.2 keycloak in docker. I replaced the keycloak.version parameter in pom.xml to my version and the result is still the same.

Thanks

**Comment by lbajada** [comment]
Hi Azimov, changing the version will most likely break compatibility and hence your issues. If this does not working with the intended version in the pom.xml, please let me know.

**Comment by kspo** [comment]
@lbajada Could you please make your repo compatible with Keycloak 24 and Java 21?

**Comment by lbajada** [comment]
@kspo It would be really nice to have this compatible with the latest Keycloak (version 25 as of now) ...if you are willing and have time to undertake this effort I will gladly review your PR first chance I get!

**Comment by kspo** [comment]
Can you please provide me a telegram address ı wanna ask some questions if its ok for u

**Comment by lbajada** [comment]
@kspo I will answer any questions or concerns publicly in this repo since it's open source.

**Comment by lbajada** [comment]
Closing issue since right now the library is not meant to work with modern versions of KC

**Comment by lbajada** [comment]
Changing to close as not planned for now
